# Generated by Django 4.1 on 2022-08-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_alter_product_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="ordered_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
