# Generated by Django 4.1 on 2022-08-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_alter_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                height_field="20", upload_to="image/", width_field="20"
            ),
        ),
    ]
