# Generated by Django 4.1 on 2022-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_alter_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(upload_to="image/"),
        ),
    ]
