# Generated by Django 4.1 on 2022-08-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0007_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                blank=True,
                choices=[("B", "Billing"), ("S", "Shipping")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="apartment_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_address",
                to="ecommerce.address",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_address",
                to="ecommerce.address",
            ),
        ),
    ]
