# Generated by Django 4.1 on 2022-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0008_address_address_type_address_apartment_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("B", "Billing"), ("S", "Shipping")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="apartment_address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address", name="zip", field=models.CharField(max_length=100),
        ),
    ]
