# Generated by Django 4.1 on 2022-08-29 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0011_userprofile"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="user",),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
